# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Mealplan' do

pod 'SDWebImage'
pod 'JSONModel'
pod 'ActionSheetPicker-3.0'
pod 'JSQMessagesViewController'

end

target 'MealplanTests' do

end

